server:
  port: 8089

#设置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.159.233.23:3306/mybatisTest
    password: root
    username: root
    hikari:
      #设置事务自动提交
      auto-commit: true
      #设置最大连接数
      maximum-pool-size: 10
      minimum-idle: 10
      #获取连接是，检测语句
      connection-test-query: select 1
      #连接超时设置
      connection-timeout: 20000
  # Redis配置
  data:
    redis:
      host: 139.159.233.23
      port: 6379
      database: 1
      # 读超时
      timeout: 3000
      # 连接超时
      connectTimeout: 5000
      # Lettuce连接池
      lettuce:
        pool:
          # 最小空闲连接
          min-idle: 5
          # 最大空闲连接
          max-idle: 10
          # 最大连接数
          max-active: 100
          # 连接分配应该阻塞的最大时间
          max-wait: 2000



  #热启动
  devtools:
    restart:
      enabled: false
      exclude: application.yml,static/**,public/**

mybatis-plus:
  configuration:
    #开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    #开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.mybatisplus.pojo
  #扫描mapper文件
  mapper-locations: classpath:mapper/*.xml

knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
production: true



